# Starter pipeline
- task: AzureMysqlDeployment@1
  inputs:
    azureSubscription: 'ltutari (a88bbbea-5bb4-4a6a-ba66-01fe3ddb3dcb)'
    ServerName: 'server01.mysql.database.azure.com'
    SqlUsername: 'Lohitha'
    SqlPassword: 'Pa$$w0rd'
    TaskNameSelector: 'InlineSqlTask'
    SqlInline: |
      - task: AzureCLI@2
        displayName: Azure CLI
        inputs:
          azureSubscription: ltutari (a88bbbea-5bb4-4a6a-ba66-01fe3ddb3dcb
          scriptLocation: inlineScript
          arguments:
            -SERVERNAME mydemoserver `
            -DBNAME pollsdb `
            -DBUSER pollsdbuser`
            -DBPASSWORD pollsdbpassword
            -INLINESCRIPT 
          inlineScript: |
            az login --allow-no-subscription
            az mysql flexible-server execute --name $(SERVERNAME) \
            --admin-user $(DBUSER) --admin-password '$(DBPASSWORD)' \
            --database-name $(DBNAME) \
            --query-text "UPDATE items SET items.retail = items.retail * 0.9 WHERE items.id =100;"
    IpDetectionMethod: 'AutoDetect'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
